name: books

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID_TO_NOTIFY: ${{ secrets.TELEGRAM_CHAT_ID_TO_NOTIFY }}
      TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
      REMOTEOK_API_URL: ${{ secrets.REMOTEOK_API_URL }}
      REMOTEOK_WEBSITE_URL: ${{ secrets.REMOTEOK_WEBSITE_URL }}
      JOB_TAGS: ${{ secrets.JOB_TAGS }}
      JOBS_PER_TAG: ${{ secrets.JOBS_PER_TAG }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.19'
    - run: npm install
    - run: npm start
